name: Auto Assign Reviewer

on:
    pull_request:
        types: [opened, reopened, ready_for_review]

jobs:
    auto-assign-reviewer:
        runs-on: ubuntu-latest

        steps:
            - name: 🏷️ Assign reviewer
              uses: ahmadnassri/action-assign-reviewers@v1.0.0
              with:
                  reviewers: fvrvz
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
